### ISSUE TITLE
Benchmark against WSL2 and native Linux

### ISSUE THREAD

**Issue by sztomi** [google/cdc-file-transfer#49]
The README describes a benchmark against Cygwin rsync as "linux rsync" which is true in some ways, but Cygwin is especially slow for I/O workloads (and slow in general). A more appropriate comparison would be comparing against WSL2 (or even WSL) rsync in a Windows environment. It would also be an interesting data point (though obviously orthogonal to the very use case of this tool) to see how it performs when compared against `rsync` in a fully native Linux environment.

**Comment by ljusten** [comment]
Is Cygwin slow on file operations in general (including raw IO) or just open and stat operations? I would assume that it doesn't affect raw IO much. The package consists of only roughly 350 files, so the overhead of file operations should be low.

I can't install WSL2 on my Windows box for security reasons, but I can test with rsync on Linux. I think it's fair to say that the WSL2 performance should be somewhere between rsync on Linux and rsync on Cygwin (ignoring the fact that my Windows box doesn't have the same CPU as the Linux box - my Windows box has 10% higher single core performance, but way less cores).

**Comment by ljusten** [comment]
The upload test with rsync on Linux is still running, but so far the results are consistent with Cygwin rsync on Windows. The upload times are somewhere between 240 and 320 seconds, which makes sense given that the CPU is slower per core and rsync's diffing algorithm is not multithreaded AFAIK.

**Comment by ljusten** [comment]
Here are the benchmark results including native Linux rsync. The results are ~35% worse than Cygwin rsync, which is most likely due to the worse single-core performance on that system (Xeon Gold 6154 @ 3.00GHz vs Xeon W-2135 @ 3.70GHz). But since the results are easy to misinterpret, I decided to not show the graph in the README.md, but leave Linux rsync a footnote.

https://github.com/google/cdc-file-transfer/blob/docs/docs/cdc_rsync_vs_cygwin_rsync_vs_linux_rsync.png

**Comment by sztomi** [comment]
Thanks for following up. Yes, my impression is that Cygwin is slow for I/O, and much slower than native linux on the same hardware. Part of the problem is that the underlying filesystem (NTFS) is really slow compared to modern filesystems like ext or btrfs. Symlinks are implemented as text files that contain the real filename, too, which is also a huge perf hit if there are many. I agree that the benchmark done on a different hardware should not be included. Are the benchmarks included in this repo? I would be happy to run them on the identical hardware if that's helpful.

**Comment by ljusten** [comment]
In my experience, read speed is fine on Windows, and since there are only 350 files in the packages, there's no big file op overhead. If Cygwin was much slower than Linux, I would expect the Linux benchmarks to be faster than the Cygwin benchmarks, but they're in fact slower due to the slower CPU (it has a 10% lower PassMark score).

The benchmarks are not included as I can't share the package data.
